### ISSUE TITLE
Landing page image/hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Liberal-Studies#1]
Hero image just needs to be sized and placed, please and thank you.

**Comment by pixelyunicorn** [comment]
Pinging @ZMcGroarty

**Comment by ZMcGroarty** [comment]
![hero_liberalstudies-min](https://cloud.githubusercontent.com/assets/15017242/24208444/fe823634-0ef9-11e7-8954-3f81749e4031.png)

**Comment by CVE82** [comment]
I'm wondering if the army guy is a little misleading, Joe and I selected that random army pic when setting up the program. Is there something that might encompass the older students we're trying to attract?

**Comment by ZMcGroarty** [comment]
Thats Mike S’s go to line “like veterans and moms returning to school”

Unfortunately, "adult education" as a stock image search gets you the worst things ever. If this doesn’t stick I can find another, but its worth a shot.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Mar 22, 2017, at 12:32 PM, Camille Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm wondering if the army guy is a little misleading, Joe and I selected that random army pic when setting up the program. Is there something that might encompass the older students we're trying to attract?

**Comment by CVE82** [comment]
Okay cool, thanks so much! =D I know we are targeting vets too just such a muddled program lol happy to let it ride!
