### ISSUE TITLE
Resize hero image please

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Liberal-Studies#4]
Hey Zac Attack whenever you get a chance can you resize the hero so the soldier is centered? Thanks a million!

**Comment by ZMcGroarty** [comment]
Try this one:

![hero_liberalstudies-min](https://cloud.githubusercontent.com/assets/15017242/25901563/2766def6-3565-11e7-8c17-fe325abc926d.png)

**Comment by CVE82** [comment]
Thanks homie!
