### ISSUE TITLE
Anthropology faculty appearing on liberal studies page

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Liberal-Studies#5]
The faculty that show up on the liberal studies page are anthro faculty. Noticed same thing on the poli sci page, too.

**Comment by CVE82** [comment]
Thanks, it's a quick fix I will adjust them tomorrow when I get back. If Chris hasn't already =)

**Comment by pixelyunicorn** [comment]
Looks like an issue in Drupal, the config file has been pointing to the correct datafiles for nearly a month:

![screen shot 2017-05-30 at 2 29 51 pm](https://cloud.githubusercontent.com/assets/607807/26598827/74a2c4d4-4544-11e7-86e2-1807104cff82.png)

**Comment by CVE82** [comment]
Yes I will adjust the settings in Drupal tomorrow when I get in, I know where it's feeding the incorrect information from. Thanks!

**Comment by CVE82** [comment]
PolySci and Lib Studies faculty is updated.
